version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "youtube"

  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - 8081:8080

